M48
; DRILL file {KiCad 8.0.1} date 2024-09-10T20:12:56-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-10T20:12:56-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.7944Y-3.7813
T2
X5.2067Y-3.7008
X5.2067Y-4.8425
M30
